language: python

python:
  - "3.6.5"

test:
  adapter: sqlite3
  database: "validators"
  timeout: 500

install:
  - pip install -e .
  - pip install django-coverage
  - pip install pytest-django
  - pip install django
  - pip install pytest-cov
  - pip install codecov

script:
  - pytest --cov-report=html --cov-config=.coveragerc  --cov=./

after_success:
  - codecov